spring:
  main:
    allow-bean-definition-overriding: true
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      auto-offset-reset: latest
  cloud:
    stream:
      default:
        group: my-spring-kafka-app
      kafka:
        binder:
          zkNodes: localhost
          brokers: localhost
          auto-create-topics: false

      bindings:
        payment-deposited:
          destination: payment-deposited
          consumer:
            headerMode: headers
            concurrency: 2
