spring:
  main:
    allow-bean-definition-overriding: true
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  cloud.stream:
    kafka:
      binder:
        zkNodes: localhost
        brokers: localhost
      bindings:
        payment-deposited-input:
          consumer:
            configuration:
              value.deserializer: com.example.project.config.kafka.PaymentDepositedDeserializer

    bindings:
      payment-deposited-input:
        destination: payment-deposited
        group: kafka-example
        consumer:
          headerMode: headers
          concurrency: 8
          batch-mode: true
      payment-deposited-output:
        destination: payment-deposited
        producer:
          headerMode: none
